### PR TITLE
Test onnx-fb-universe with moved setup.py.

### PR DESCRIPTION
**Pull request by orionr**
* Point to https://github.com/caffe2/caffe2/pull/2468 and modify scripts.

### CODE REVIEW

**Comment by orionr** [comment]
@onnxbot test this please

**Comment by bddppq** [comment]
@onnxbot test this please

**Comment by orionr** [comment]
Looks like a transient `pytorch` repo failure.

@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@orionr could you add yourself to the whitelist?

**Comment by orionr** [comment]
@onnxbot retest this please

**Comment by orionr** [comment]
@onnxbot retest this please

**Comment by orionr** [comment]
Looks like I can change
```
_pip_install -b "$BUILD_DIR" "file://$REPOS_DIR/caffe2#egg=caffe2&subdirectory=caffe2"
```
to
```
_pip_install -b "$BUILD_DIR/caffe2" "file://$REPOS_DIR/caffe2#egg=caffe2&subdirectory=caffe2"
```
and it still works. Just FYI.

**Comment by orionr** [comment]
We decided to rename instead - closing.

**Pull request closed without merging**
