### PR TITLE
No expect

### PR DESCRIPTION
**Pull request by anderspapitto**
you can review just the top commit - bottom commit just deletes expect files

### CODE REVIEW

**Comment by houseroad** [comment]
Do we plan to move both test_models.py and test_caffe2.py to pytorch/caffe2 main repo?

If so, I would suggest to merge these two files together. Call it caffe2 test_onnx_e2e.py?

If it is possible, we should still have expect files for each operator exporting test (exported from pytorch).

**Comment by bddppq** [comment]
Thanks for working on this!

Why are the PyTorch-generated.* expect files deleted? @houseroad are they generated when you scrape the pytorch tests to onnx?
Looks like there are some TestOperators expect files got deleted, I think they are used by test_operators.py? We don't need to get rid of expect files for these tests.
There are still some TestModels expect left.

**Comment by houseroad** [comment]
@bddppq , yes, PyTorch-generated.* are generated by my converting scripts. BTW, I should move those scripts to pytorch/caffe2 repo, since this repo is going to be deprecated. I will do that soon. :-)

**Comment by anderspapitto** [comment]
@bddppq yeah, that's what I've currently done - removed the expect files for only the model tests

**Pull request merged**
