### PR TITLE
[auto] onnx-pr-469

### PR DESCRIPTION
**Pull request by onnxbot-worker-2**
This is an auto PR managed by onnxbot for tracking

https://github.com/onnx/onnx/pull/469 setup cmake

### CODE REVIEW

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by houseroad** [comment]
@onnxbot retest this please :-)

**Comment by bddppq** [comment]
@onnxbot retest this please

**Pull request closed without merging**
