### PR TITLE
[auto] pytorch-pr-6566

### PR DESCRIPTION
**Pull request by o8ht88z00f**
This is an auto PR managed by onnxbot for tracking

https://github.com/pytorch/pytorch/pull/6566 enable exporting bidirectional rnn with fixes seq len from onnx to caffe2

### CODE REVIEW

**Comment by anderspapitto** [comment]
@onnxbot retest this please

**Comment by houseroad** [comment]
@onnxbot retest this please

**Comment by houseroad** [comment]
@onnxbot

**Comment by houseroad** [comment]
@onnxbot retest this please

**Pull request closed without merging**
