### PR TITLE
[auto] pytorch-pr-5367

### PR DESCRIPTION
**Pull request by onnxbot-worker-1**
This is an auto PR managed by onnxbot for tracking

https://github.com/pytorch/pytorch/pull/5367 add @torch.jit.script, @torch.jit.compile, torch.jit.CompilationUnit(str)

### CODE REVIEW

**Comment by soumith** [comment]
@onnxbot retest this please

**Comment by zdevito** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Pull request closed without merging**
