### PR TITLE
[auto] pytorch-pr-4922

### PR DESCRIPTION
**Pull request by onnxbot-worker-1**
This is an auto PR managed by onnxbot for tracking

https://github.com/pytorch/pytorch/pull/4922 [WIP] Layer Normalization

### CODE REVIEW

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by bddppq** [comment]
@onnxbot retest this please

**Comment by SsnL** [comment]
@onnxbot retest this please

**Comment by SsnL** [comment]
@onnxbot retest this please

**Comment by SsnL** [comment]
@onnxbot retest this please

**Comment by SsnL** [comment]
@onnxbot retest this please

**Comment by houseroad** [comment]
@onnxbot retest this please

**Pull request closed without merging**
